# /opt/navpage/cloudflared-config/config.yml
tunnel: $TUNNEL_ID
credentials-file: /root/.cloudflared/$TUNNEL_ID.json

ingress:
  - hostname: nav.apescope.com
    service: http://localhost:5000
  - service: http_status:404